### ISSUE TITLE
Code Review 15.02.

### ISSUE THREAD

**Issue by alottamonkeys** [PlatinumFoxTail/MachineLearning_NeuralNetwork#1]
I have downloaded and inspected the code on the 15.02. However, I could not run the code because I could not install pipx, there seem to be some problems with xcode dev tools.

## General
I found this project to have a nice set up and structure. I want to mention a few points that positively stood out to me
- You have automated testing with a CI pipeline, the tests don't fail
- You used a dependency management tool

A few things could be improved/that I noticed
- a better description in the readme would help to understand the project
- you could consider using a venv for your dependencies, also for poetry, I believe. However, I have no experience with poetry.
- It seems like you only work on main. I know this is a one-person-project, but you may like structuring the project into feature branches for better overview. However, this would be for your convenience only. 

## network.py
I like the structure of the Network class, it is very comprehensive. 
I noticed a few things that could be improved 
- naming of variables seems not as comprehensive to me at times (->  e.g. nabla_b, nabla_w, eta, nb, ...)
- you have duplicate code in lines 79-80 and 93-94
- if you would like to test different activation functions, you may want to pass an argument that determines the activation function. I think that could also be interesting
- Your feedforward method could be used in the training process, then you would not need near duplicate code in lines 102-106. To me this looks like another implementation of forward pass, however I could not debug this.
- in the feedforward method you overwrite a each iteration ?
- you have some methods that would usually not need to be called from outside of the class. Maybe consider making them private
- I see that the interface you provide here is different from the interface that you provide in the SimpleNetwork. You could consider defining an interface used by both

## simple_network.py
You have written a basic Network implementation with one hidden layer. You used an object oriented approach, which is consistent with the other network class.
A few things I noticed:
- You have some duplicate code. The implementations of sigmoid and sigmoid_prime are the same as in network.py. Maybe put them in a separate file and import that?
- Everything here is hardcoded. I think it could be interesting to investigate using different number of iterations, different hidden layer size, etc.

## benchmark_network.py
In this file you benchmark both of your network classes.
I noticed the following
- I think it would be best practice to put the code in the end of the file in a __main__ method
- The code that creates the plot seems to be near duplicate. You could have a plot_network method for this
- I don't understand why you do not use the training method provided by your network class. 

## jupyter notebook
I like the idea of using the notebook!
In my opinion you did a good job explaining the code. I also like that the user can choose the numbers. Looks like a fun experience. I noticed nothing else. 

Best, Lotta

**Comment by PlatinumFoxTail** [comment]
Hi Lotta,

Thanks for the feedback. Many good points that I'll take with me when refining the project further.

Would you mind still to elaborate a bit on " I could not run the code because I could not install pipx, there seem to be some problems with xcode dev tools"? What kind of possible error message do you get if you follow the instruction on how to run the program described in the manual document (https://github.com/PlatinumFoxTail/MachineLearning_NeuralNetwork/blob/main/documents/manual.md)? 

Kind regards,

//Martin

**Comment by alottamonkeys** [comment]
Hi Martin,

I don’t think this has anything to do with your documentation. I did not get any error message, the problem might as well have been the internet connection at my dorm. However, I needed to install poetry to run your code, for this I would need pipx. Homebrew could not install pipx because it found some error with xcode. I yould not re-download xcode for an unknown reason. Im sorry, but I did not and dont have the time to investigate this much further.

Best,
Lotta

Am 16.02.2024 um 13:04 schrieb Martin Häggblom ***@***.***>:



Hi Lotta,

Thanks for the feedback. Many good points that I'll take with me when refining the project further.

Would you mind still to elaborate a bit on " I could not run the code because I could not install pipx, there seem to be some problems with xcode dev tools"? What kind of possible error message do you get if you follow the instruction on how to run the program described in the manual document (https://github.com/PlatinumFoxTail/MachineLearning_NeuralNetwork/blob/main/documents/manual.md)?

Kind regards,

//Martin

**Comment by PlatinumFoxTail** [comment]
Thanks once again for giving an extra explanation. Thanks for the valuable comments, I will implement as much as times allows. In the meantime I will close this issue. Wish you a great spring ahead.
