### ISSUE TITLE
Review 2, 24.2.2024

### ISSUE THREAD

**Issue by Deeroil** [PlatinumFoxTail/MachineLearning_NeuralNetwork#2]
# Review 2

project cloned 24 Feb, 2024, 13:40

I'm not familiar with Jupyter Notebook, which is why figuring out how to run the program felt clunky. Eventually I got it to work after trial and error, at first I couldn't get the input to work (maybe I ran the blocks as separate? not sure).

I like the way the steps are explained in the Jupyter file / UI.

The pytests run like intended.

I like the comments in the code, though some of them could be docstrings and I overall think docstrings would be nice, to explain the variable names etc. eta for example is explained in one place but could be 

As I'm not a math-oriented person, I had to google some stuff and I still don't understand what's happening more than on a very surface level ML understanding.

Good job overall with the project.

**Comment by PlatinumFoxTail** [comment]
Thanks for the commment. I updated the manual document to specify further how to run the notebook. I will close this issue now, so wish you a great spring ahead.
